openapi: "3.0.0"
info:
  version: 1.0.0
  title: announcement-app-api
paths:
  /announcement:
    get:
      summary: List announcements
      description: Returns list of announcements
      responses:
        '200':
          description: announcements response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Announcement'
      x-amazon-apigateway-integration:
        uri: ${lambda_integration_uri_list_announcements}
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Creates a new Announcement. Duplicates are allowed
      operationId: addAnnouncement
      requestBody:
        description: Announcement to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAnnouncement'
      responses:
        '201':
          description: announcement response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Announcement'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-amazon-apigateway-integration:
        uri: ${lambda_integration_uri_create_announcement}
        responses:
          default:
            statusCode: "201"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"

components:
  schemas:
    Announcement:
      type: object
      required:
        - title
        - date
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        date:
          type: string
          format: date-time
    NewAnnouncement:
      type: object
      required:
        - title
        - date
      properties:
        title:
          type: string
        description:
          type: string
        date:
          description: The announcement date and time in UTC format e.g. 2011-11-04 23:12
          type: string
          format: date-time
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string